name: password_manager
description: "A Flutter app to manage passwords."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  local_auth: ^2.1.8
  material_symbols_icons: ^4.2719.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  encrypt: ^5.0.3
  file_picker: ^8.0.3
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter:
  assets:
    - assets/logo/
    - .env
  uses-material-design: true

flutter_icons:
  image_path: "assets/logo/icon.png"
  adaptive_icon_foreground: "assets/logo/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#0E0E0E"

flutter_native_splash:
  color: "#FCFDF6"
  color_dark: "#1A1C19"
  image: "assets/logo/light.png"
  image_dark: "assets/logo/dark.png"
  android: true
  ios: true
